HAI 1.2
I HAS A VAR
GIMMEH VAR
VAR IS NOW A NUMBR
DIFFRINT 0 AN MOD OF VAR AN 2, O RLY?
    YA RLY
        VISIBLE "Weird"
    MEBBE BOTH SAEM VAR AN BIGGR OF 2 AN SMALLR OF VAR AN 5 BTW n == max(min(n, 5),2) ; 2 <= n <= 5
        VISIBLE "Not Weird"
    MEBBE BOTH SAEM VAR AN BIGGR OF 6 AN SMALLR OF VAR AN 20 BTW n == max(min(n, 20),6) ; 6 <= n <= 20
        VISIBLE "Weird"
    NO WAI
        VISIBLE "Not Weird"
OIC
KTHXBYE
